version: "3"

services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "td"
      POSTGRES_DB: "exam"
    restart: "on-failure"
  manage:
    build:
      context: "./manager"
      dockerfile: "dockerfile"
    image: "manage:latest"
    environment:
      CSV_FILENAME: "data.csv"
    ports:
      - "3000:5432"
    depends_on:
      - "db"
    restart: "on-failure"