version: "3"

services:
  db:
    image: "postgres:latest"
  manage:
    build:
      context: "./manager"
      dockerfile: "dockerfile"
    image: "manage:latest"
    environment:
      CSV_FILENAME: "data.csv"
    ports:
      - "3000:5432"
    depends_on:
      - "db"
  